GET http://localhost:9090/api/v1/health-check

### Save book
POST http://localhost:9090/api/v1/books
Content-Type: application/json

{
  "title": "Harry Potter and Prisoner of Azkaban",
  "description": "Harry Potter and Prisoner of Azkaban - Third book in the Harry potter series",
  "published": true
}

### Save book
POST http://localhost:9090/api/v1/books
Content-Type: application/json

{
  "title": "Harry Potter and the Order of the Phoenix",
  "description": "Harry Potter and Prisoner of Azkaban - Fifth book in the Harry potter series",
  "published": true
}

### Save books
POST http://localhost:9090/api/v1/books
Content-Type: application/json

{
  "title": "Dummy book",
  "description": "Dummy book - This is a book entry",
  "published": false
}

### Get all Books
GET http://localhost:9090/api/v1/books

### Get Book by id
GET http://localhost:9090/api/v1/books/3

### Get Book by title pattern
GET http://localhost:9090/api/v1/books/title/potter